apiVersion: kaspr.io/v1alpha1
kind: KafkaMessageScheduler
metadata:
  name: my-scheduler
spec:
  replicas: 1
  bootstrapServers: localhost:9092
  tls: {}
  authentication:
    type: plain
    username: kafka-user
    passwordSecret:
      secretName: kafka-credentials
      passwordKey: password
  storage:
    type: persistent-claim
    class: standard
    size: 256Mi
    deleteClaim: False