apiVersion: kaspr.io/v1alpha1
kind: KasprAgent
metadata:
  name: my-agent1
  labels:
    # The kaspr.io/app label identifies the KasprApp instance
    # in which to create this agent.
    kaspr.io/app: my-app
spec:
  description: My agent
  inputs:
    topic:
      names:
        - my-topic1
        - my-topic2
      #pattern: my-topic*
      keySerializer: raw
      valueSerializer: raw
    # channel:
    #   name: my-channel
  processors:
    pipeline:
      - reformat
    init:
      python: |
        import uuid
        resume = { 'name': "greg" }
    operations:
      - name: reformat
        map:
          python: |
            def simplify(event):
                #print(Resume: {resume})
                #event['resume'] = resume
                return event
