apiVersion: kaspr.io/v1alpha1
kind: KasprAgent
metadata:
  name: my-agent1
  namespace: kaspr
  labels:
    # The kaspr.io/app label identifies the KasprApp instance
    # in which to create this agent.
    kaspr.io/app: my-app
spec:
  description: My agent
  input:
    topic: 
      name: web-transactions
      #pattern: my-topic*
      #keySerializer: raw
      valueSerializer: json
    # channel:
    #   name: my-channel
  output:
    topics:
      - name: large-transactions
        keySerializer: raw
        valueSerializer: json
        keySelector:
          python: |
            def get_key(value):
              return str(value)
        valueSelector:
          python: |
            def get_value(value):
              return str(value) + "NOOO"
        predicate:
          python: |
            def filter(value):
              return value > 10        
  processors:
    pipeline:
      - split
      - increase
      - add-one
      # - multiply
      # - odd-numbers
    init:
      python: |
        import uuid
        ids = [ str(uuid.uuid4()), str(uuid.uuid4()), str(uuid.uuid4()) ]
    operations: 
      - name: split
        map:
          python: |
            def split(transaction):
              yield 2
              yield 3
              yield 10
              yield 20
      - name: increase
        map:
          python: |
            def adding(value):
              yield value + 1
              yield value + 3
              yield value + 6
              yield value + 9
      - name: add-one
        map:
          python: |
            def adding(value):
              return value + 1