apiVersion: kaspr.io/v1alpha1
kind: KasprWebView
metadata:
  name: my-webview1
  namespace: kaspr
  labels:
    # The kaspr.io/app label identifies the KasprApp instance
    # which hosts this webview
    kaspr.io/app: my-app
spec:
  name: grafana-webhook-receiver
  description: A webview that receives Grafana webhook alerts and forwards them to a Kafka topic.
  request:
    method: POST
    path: /grafana-webhook-receiver
  response:
    contentType: application/json
    bodySelector:
      onSuccess:
        python: |
          def get_body(value):
            return {
              "status": "success",
              "message": "Webhook received and forwarded to Kafka topic."
            }
      onError:
        python: |
          def get_body(error):
            return {
              "status": "error",
              "message": "Failed to forward webhook to Kafka topic."
            }
