apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kaspragents.kaspr.io
spec:
  scope: Namespaced
  group: kaspr.io
  names:
    kind: KasprAgent
    plural: kaspragents
    singular: kaspragent
    shortNames:
      - kagents
      - kagent
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                description:
                  type: string
                  description: A short description of what this agent does.
                inputs:
                  description: Inputs to stream processing.
                  type: array
                  items:
                    type: object
                    properties:
                      topic:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the topic to read from.
                          partitions:
                            type: integer
                            minimum: 1
                            description: The number of partitions in the topic.
                        required:
                          - name
                          - partitions
                      channel:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the channel to write to.
                        required:
                          - name
                    anyOf:
                      - required:
                          - topic
                      - required:
                          - channel
                outputs:
                  description: Outputs to stream processing.
                  type: array
                  items:
                    type: object
                    properties:
                      topic:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the topic to read from.
                          partitions:
                            type: integer
                            minimum: 1
                            description: The number of partitions in the topic.
                        required:
                          - name
                      channel:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the channel to write to.
                        required:
                          - name
                    anyOf:
                      - required:
                          - topic
                      - required:
                          - channel
              required:
                - inputs
                - outputs
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true