apiVersion: kaspr.io/v1alpha1
kind: KasprApp
metadata:
  name: my-app
  labels:
    domain: sales
spec:
  version: 0.1.2
  replicas: 1
  bootstrapServers: localhost:9092
  authentication:
    type: plain
  config:
    topicPartitions: 3
    webPort: 6065
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 1
      memory: 128Mi
  storage:
    type: persistent-claim
    class: standard
    size: 256Mi
    deleteClaim: True