# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  # Default values for kaspr-operator
  enable: True

  namespaceOverride: ""

  # Set to `True` if you want the operator to be "cluster-wide" and operate over all namespaces.
  # If false, 
  watchAnyNamespace: False

  # Specific namespace to watch over. The namespace the operator is deployed to is automatically included.
  # If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
  # the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
  watchNamespaces: []

  rbac:
    # Set to `yes` to create all necessary roles and role bindings for the operator to function.
    # Otherwise, you will need to manage RBAC manually.
    create: yes
  createGlobalResources: true

  image:
    repository: kasprio/kaspr-operator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP  
    port: 80

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  nodeSelector: {}

  tolerations: []

  affinity: {}
